### ISSUE TITLE
NoneType for property result while getting from get_wallet_balance 

### ISSUE THREAD

**Issue by ireccode** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#3]
Traceback (most recent call last):
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/i303832/.local/share/virtualenvs/TV2BybitBOT-469t8JvM/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/i303832/Documents/docs/Crypto/krypto/inBOT/TV2BybitBOT/webhook-bot.py", line 48, in webhook
    send_order(datas)
  File "/Users/i303832/Documents/docs/Crypto/krypto/inBOT/TV2BybitBOT/actions.py", line 96, in send_order
    print(wallet_balance['result']['BTC']['available_balance'])
TypeError: 'NoneType' object is not subscriptable

**Comment by Mtemi** [comment]
What does line 87 print for you and how does your data dictionary look like ?

**Comment by crypttops** [comment]
Clone current update

**Comment by Mtemi** [comment]
Solved via repo update
