### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by mikeh21** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#7]
{"symbol": BTCUSD, "amount": 10, "type": Market, "side": Buy, "key": "*********************"}
34.xxx.xx.xx - - [02/Feb/2021 21:35:25] "POST /webhook HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/bybot/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook/webhook-bot.py", line 47, in webhook
    if get_token() == datas['key']:
TypeError: string indices must be integers

Hi, any advice what the problem could be? taken from debug after sending test webhook from TV.

key is redacted but was generated from generate_alert_message.py

Thanks

**Comment by JTD420** [comment]
If you go to `webhook-bot.py` & find the line that defines the `datas` variable. Just on top of it is an almost identical version which is commented out with a `#`.

Try uncommenting that and commenting the current `datas` variable and it should fix that problem!

(theres other issues with this code I'm still working through but hope that helps you if you're still trying to get it to work.) 👍

**Comment by mikeh21** [comment]
This resolves the issue, thank you

**Comment by VRPlayhouse** [comment]
I had the same issue, and tried this fix but it didn't work.
